### PR TITLE
refactor(angular/tooltip): simplify shadow definitions

### PR DESCRIPTION
**Pull request by jeripeierSBB**

### CODE REVIEW

**Review by kyubisation — CHANGES_REQUESTED** [review]
Some change broke the positioning of the arrow when the tooltip is shown below the trigger.
image
image

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
image
image

**Comment by kyubisation** [comment]
Nice work 😃

**Review by mhaertwig — APPROVED** [review]
LGTM 👍

**Pull request merged**
