### PR TITLE
fix(journey-maps/web-component): export the web-component 

### PR DESCRIPTION
**Pull request by swiss-chris**
Refs: ROKAS-1137

### CODE REVIEW

**Review by mhaertwig — APPROVED** [review]
Please don't write the internal Ref in the commit message.
Otherwise LGTM 👍

**Review by kyubisation — APPROVED** [review]
LGTM 👍

**Comment by swiss-chris** [comment]
> Please don't write the internal Ref in the commit message. Otherwise LGTM 👍

Is there any way to include the JIRA story number in the git history ?

**Review by sbboli — APPROVED** [review]

**Comment by mhaertwig** [comment]
> > Please don't write the internal Ref in the commit message. Otherwise LGTM 👍
> 
> Is there any way to include the JIRA story number in the git history ?

No, we usually don't do it. I think the PR and the code should be self-explanatory.

**Comment by swiss-chris** [comment]
> > > Please don't write the internal Ref in the commit message. Otherwise LGTM 👍
> > 
> > 
> > Is there any way to include the JIRA story number in the git history ?
> 
> No, we usually don't do it. I think the PR and the code should be self-explanatory.

Playing devil's advocate: what's the disadvantage of including the story number in the commit message (under refs) ?
The advantage: in certain cases, e.g. when fixing a bug, it might require a lot of explanations of what exactly was the bug that this commit fixes, and it would be easier to include that detail, including photos, in a jira ticket rather than the commit message.

**Comment by mhaertwig** [comment]
Okay, seems that I was too strict. 😉 I discussed this internally and according to @kyubisation it's okay if the reference is in the commit body.

**Pull request merged**
